@startuml

skinparam rectangle {
  RoundCorner 15
  BorderColor #006064
  FontColor #000000
}

skinparam note {
  BorderColor #006064
  FontColor #000000
  BackgroundColor #ffc0cb
  RoundCorner 15
}

' --- Nœud principal ---
rectangle "Projet NLP\n" as ProjetNLP #white

' --- Questions ---
rectangle "Question 1 : Dans quelle mesure le sentiment des investisseurs\nhaussier vs baissier peut-il être prédit à partir\ndu texte d'un post sur StockTwits ?\n" as Q1 #e0f7fa

rectangle "Question 2 : À quel point les étiquettes Haussier/Baissier\nsont-elles informatives sur les mouvements futurs\ndes cours des actions ?\n" as Q2 #e0f7fa

rectangle "Question 3 : Le sentiment inféré automatiquement\nconserve-t-il la même information ?\n" as Q3 #e0f7fa

rectangle "Question 4 : Les informations des réseaux sociaux\naméliorent-elles la prédiction des mouvements\ndu marché par rapport aux prix historiques seuls ?\n" as Q4 #e0f7fa

rectangle "Question 5 : Quels types de messages font que les modèles NLP\nréussissent ou échouent, et quand le sentiment exprimé\nne correspond-il pas aux mouvements de marché suivants ?\n" as Q5 #e0f7fa




note right of Q1
Dans l'article de StockTwits, ils ont utilisé un modele bigramme un peu ancien :
on peut donc espérer faire mieux qu'eux avec les transformers vus en cours.
end note

rectangle "création du modèle d'analyse de sentiment pour HAUSSE/BAISSE" as Q1_task_1 #e0ff1a


note bottom of Q1_task_1
On récupère ce que l'on a fait en TP : on récupère un modèle
adapté et on le finetune pour obtenir un sentiment HAUSSE ou BAISSE.

Le modèle AutoModelForSequenceClassification.from_pretrained(
microsoft/mpnet-base, num_labels=2) semble adapté.

Le token CLS contient le sens global du tweet.

Une couche Dense + softmax donne HAUSSE ou BAISSE.

Comme il y a beaucoup plus de HAUSSE que de BAISSE,
il faut une loss qui pénalise davantage les erreurs BAISSE.
Voir faire de la data augmentation sur les BAISSE.

Option : geler le transformer préentraîné puis finetuner ensuite.

Le résultat est un réseau dédié uniquement au label.
end note


rectangle "Création d'un DataFrame contenant les informations nécessaires\nDF(date, code_titre, nombre_tweets_hausse, nombre_tweets_baisse, mouvement_J1, mouvement_J3, mouvement_J7, mouvement_J30)" as Q1_task_2 #e0ff1a


note bottom of Q1_task_2
  On récupère les données des csv, les deux seuls csv intéressants que je vois sont :

  - msg_000.csv
  messages: message_id, message_body  

  - sentiment_00.csv
  sentiments: message_id, user_id, created_at, sentiment, symbol_list  

  Procédure :
   - symbol_list sera à splitter pour créer plusieures lignes (on normalise ...)
   - created_at : transformé en un numéro de jours après le début des données
   - user_id, sentiment, symbol : transformation en type plus simples
   - on filtre pour ne garder que certains symboles qui nous intéressent

  Le dataframe est sauvegardée avec un nom qui contient la liste de symbole
  Il est notre point d'entrée pour toutes nos analyses
end note

note bottom of Q1_task_2
  Récupération les mouvements des titres via yfinance pour les 5 horizons de temps (J1, J3, J7, J30) 
  et créer un df dédié "mouvements" symbol, date, mouvement_J1, mouvement_J3, mouvement_J7, mouvement_J30.
  Jx est un booléen pour dire HAUSSE ou BAISSE apres x jours ouvrés
end note

note bottom of Q1_task_2
  Avoir une table de test pour tester nos modèles sur 100 tweets bien équilibrés HAUSSE/BAISSE :
  - 40 "faciles" : sentiments de la table = sentiments prédit par le modèle de l'article (25 hausses 25 baisses)
  - 30 "moyen" : sentiments avec prédictions fausses avec le modèle de l'article mais ok avec le modèle FinBert
  - 30 "dur" : sentiments avec prédictions fausses par FinBert et prédit par humain et sans sarcasmes
  Cela donne une note de 0 à 100 pour un modèle que l'on pourrait créer
end note

rectangle "on essaye de reproduire ce que l'article propose" as Q2_task_1 #e0ff1a


note bottom of Q2_task_1
On doit utiliser le modèle de la question 1 pour avoir bien plus d'étiquettes
pour notre entraînement.
on mouline le df message pour obtenir les sentiments HAUSSE/BAISSE que l'on ajoute au df sentiment si manquant dans ce df
on retire les colonnes inutiles.
on crée ainsi un df sentiment_complet
end note

note right of Q2_task_1
c'est à dire les liens entre :
- ratios hausse / mouvements
- ratios hausse / std(mouvements)
- nombre de tweets / mouvements
- nombre de tweets / std(mouvements)
- nombre de tweets HAUSSE / mouvements
- ensuite on peut explorer d'autres relations possibles
pour cette question je pense qu'une simple analyse de correlation suffit
end note




note bottom of Q3 
Si on compare les labels inférés aux labels déjà existants, on verra des différences dans certains cas.
il sera intéressant de voir les tweets correspondant et en déduire comment notre modèle travaille et ce
qu'il fait vraiment remonté. on en a besoin pour comprendre si nos cela peut induire un problème de
prévision du prix, ou même l'améliorer : certains tags utilisateurs peuvent être juste érronés ... 
On peut ajouter une matrice de confusion dans notre analyse. voir aussi si la performance est meilleur 
en remplacant les tags connus par les tags générés. 
end note

note bottom of Q4
J'ai l'impression que l'on peut rajouter ajouter d'autres éléments pour prédire le prix.
(Mais la question n'est pas claire)
Si on part la dessus : 
- on peut ajouter un embedding pour représenter l'auteur (une moyenne des embedding de ses twwets
 d'avant ce que l'on cherche à prédire par exemple; complété par une moyenne générale si trop peu
 de tweet pour un utilisateur a un instant t)
- information sur l'utilisateur, donner plus ou moins de poids aux messages s'ils ne sont que des
 réponses
- etc ...
La on part déjà sur un petit réseau de neurone si on suit cette route.
end note


note right of Q5
A voir plus tard, mais j'aimerai bien ajouter un score de précision sur chaque utilisateur 
pour pondérer son sentiment. le score de précision ne serait pas sa fréquence de réussite mais
plutot son potentiel avec un score MCC (Matthews Correlation Coefficient) à la place.
Car il faut bien comprendre que la periode considérée est haussiere et donc comme dit l'article,
 un utilisateur qui envoie toujours des message HAUSSE aurai tres souvent raison. 
Une analyse de la correlation pourrait alors montrer que c'est mieux avec cette pondération et
ca serait un début de réponse à la question : certains utilisateurs ne sont pas performants.
apres est-ce que l'on peut détecter cela dans le message en lui même : il faut voir si l'embedding 
d'un message permet de prédire une erreur de prédiction du sentiment associé... 
end note

' --- Liens ---
ProjetNLP -down-> Q1
ProjetNLP -down-> Q2
ProjetNLP -down-> Q3
ProjetNLP -down-> Q4
ProjetNLP -down-> Q5
Q1 -down-> Q1_task_1
Q1 -down-> Q1_task_2
Q2 -down-> Q2_task_1


@enduml
